#!/bin/bash
#multiplication  of two variables
echo "enter the first number "
read x
echo "enter the second number "
read y
z=$(($x*$y))
#this is the product of two variables
echo "the product od $x and $y is $z"
